version: "3.9"

services:
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /src:/src/app/clients/intent_grpc
      INTENT_SERVICE_HOST: intent-service
      INTENT_SERVICE_PORT: 50051
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: gpt-oss:20b
    depends_on:
      - intent-service
    networks:
      - public_net
      - internal_net

  intent-service:
    build:
      context: ./intent_service
      dockerfile: Dockerfile
    container_name: intent-service
    ports:
      - "50051:50051"
    environment:
      GRPC_PORT: 50051
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      INTENT_MODEL_NAME: gpt-oss:20b
    networks:
      - internal_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banking-frontend
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://api-gateway:8000
    depends_on:
      - api-gateway
    networks:
      - public_net
    
networks:
  public_net:
    name: banking_public_net
  internal_net:
    name: banking_internal_net
